services:
  redis:
    image: redis:7-alpine
    container_name: llm-maps-redis
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    networks:
      - llm-maps-network

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: llm-maps-backend
    ports:
      - "5000:5000"
    environment:
      - NODE_ENV=production
      - REDIS_HOST=redis
      - LLAMA_API_URL=http://host.docker.internal:11434/api
    extra_hosts:
      - "host.docker.internal:host-gateway" # For Linux
    env_file:
      - .env
    volumes:
      - ./backend:/app
      - /app/node_modules
    depends_on:
      - redis
    networks:
      - llm-maps-network

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: llm-maps-frontend
    ports:
      - "3000:80"
    env_file:
      - frontend/.env
    depends_on:
      - backend
    networks:
      - llm-maps-network

networks:
  llm-maps-network:
    driver: bridge

volumes:
  redis_data:
